include:
  - /commons/.gitlab-ci.yml
  - /hoa-microservice/.gitlab-ci.yml
  - /notifications-microservice/.gitlab-ci.yml
  - /activity-and-election-microservice/.gitlab-ci.yml
  - /user-microservice/.gitlab-ci.yml
