image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

gradle_build:
  extends: .build_cached
  stage: build
  cache:
    policy: pull-push
  artifacts:
    name: build
    expire_in: 6 hours
    paths:
      - build/
  script:
    - gradle build testClasses

# Default build cache settings to extend from
.build_cached:
  cache:
    key: "gradle-build"
    paths:
      # Only cache the gradle directory, as we do not use a shared cache
      - .gradle/
    policy: pull

build-activity-and-election-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: build
  script:
    gradle activity-and-election-microservice:assemble activity-and-election-microservice:testClasses

checkStyle-activity-and-election-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: staticAnalysis
  script:
    gradle activity-and-election-microservice:checkstyleMain activity-and-election-microservice:checkStyleTest

PMD-activity-and-election-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: staticAnalysis
  script:
    gradle activity-and-election-microservice:pmdMain

test-activity-and-election-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: test
  script:
    - gradle activity-and-election-microservice:test activity-and-election-microservice:jacocoTestReport
    - cat activity-and-election-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
